# Версия docker-compose
version: '3.3'
# Объявление сервисов/контейнеров
services:
    # Нименование сервисов/контейнеров
    nginx:
        # Наименование образа из hub.docker
        image: nginx:1.15.9
        # Имя сервисов/контейнеров
        container_name: nginx
        # Проброс портов из хоста в контейнер
        ports:
            - "80:80"
        # Проброс директорий из хоста в контейнер
        volumes:
            - "./docker/nginx/hosts:/etc/nginx/conf.d"
            - "./docker/nginx/logs:/var/log/nginx"
        
    php:
        image: php:7.3.3-fpm-stretch
        container_name: php
        ports:
            - "9000:9000"
        volumes:
            - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./docker/php/www:/var/www/html"

    mysql:
        image: mysql:8.0.15
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - "./docker/mysql:/var/lib/mysql"
        environment:
            - MYSQL_DATABASE=mysql
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=root
            - MYSQL_PASSWORD=secret
